### ISSUE TITLE
大佬你好，代码配置环境requirements.txt时pytorch版本号一直报错，我在wls2和windows都报错呜
不知道是什么特别原因

### ISSUE THREAD

**Issue by ShallowU** [orion-orion/FedDCSR#2]

**Comment by orion-orion** [comment]
Hello~不是大佬，你需要保证你的Python版本为3.8.13才能检索到到1.7.1的Pytorch版本╮(╯▽╰)╭你在命令行终端输入命令
```bash
pip install torch==
```
可以看到当前环境下可以安装的Pytorch版本（注意是`pip install torch`，不是`pip install pytorch`，连我刚刚都掉进了这个坑里哈哈）。我在Linux服务器上自己的环境里测试输出如下：
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement torch== (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1)
ERROR: No matching distribution found for torch==
```
其实用其它版本的Pytorch也可以，但你需要把代码里所有关于张量形如`x += y`的操作修改为`x = x + y`，而且此时实验结果会和论文有点出入，不过问题不大（我发现这个版本问题时论文实验已经跑完了，论文也快截稿了，就懒得改了。。。）

**Comment by ShallowU** [comment]
# requirements.txt里写pytorch应该改成torch？好像写错了哈哈哈
 @orion-orion

**Comment by orion-orion** [comment]
对。。。这玩意太坑人了，我记得还有个类似的是`pip install scikit-learn`，而不是`pip install sklearn`。。。
