### ISSUE TITLE
能分享一下数据集下载的amazon的网页吗

### ISSUE THREAD

**Issue by chenzehao82** [orion-orion/FedDCSR#4]
能分享一下数据集下载的amazon的网页。
作为刚入门的同学，我想知道amazon food 我在amazon中没找到相关的，请问这个连接是什么   https://jmcauley.ucsd.edu/data/amazon/  这个里面没找到

**Comment by orion-orion** [comment]
你好，是这个链接呢。你要拉到下面的Amazon Product Reviews部分，去进一步选择Amazon Reviews 2014，链接如下：[Amazon Reviews 2014](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html)，然后选择Grocery and Gourmet Food领域的数据集点击下载即可~

**Comment by chenzehao82** [comment]
谢谢&nbsp;


陈泽豪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hongyu ***@***.***&gt;; 
发送时间: 2024年9月22日(星期天) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [orion-orion/FedDCSR] 能分享一下数据集下载的amazon的网页吗 (Issue #4)














 
你好，是这个链接呢。你要拉到下面的Amazon Product Reviews部分，去进一步选择Amazon Reviews 2014，链接如下：Amazon Reviews 2014，然后选择Grocery and Gourmet Food领域的数据集点击下载即可~

**Comment by orion-orion** [comment]
不客气~(#^.^#)
